apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-appliaction
  labels:
    app: python-web-appliaction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-web-appliaction
  template:
    metadata:
      labels:
        app: python-web-appliaction
    spec:
      containers:
      - name: python-web-appliaction-ink8s
        image: yashwanthgowda123/newimagepython-pallication:latest
        ports:
        - containerPort: 8000
