apiVersion: v1
kind: Service
metadata:
  name: python-web-appliaction
spec:
  type: NodePort
  selector:
    app: python-web-appliaction
  ports:
    - name: python-web-appliaction-services
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30007
